name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: '@material/web'
          release-as: 1.0.0-alpha.3
          prerelease: true
          bootstrap-sha: 41d41cc2788f237f376d32409f51ca59e9b2bf75
